language: python
python:
  - "3.6"

script: 
- python -m unittest discover --start-directory ./enviro/compute_tests
- bash ./deploy_docs.sh

env:
    global:
    - ENCRYPTION_LABEL: "2d371be78117"
    - COMMIT_AUTHOR_EMAIL: "virocon@uni-bremen.de"
    

notifications:
  email:
    - a.haselsteiner@uni-bremen.de
    - kawindme@uni-bremen.de
    - janlehmk@uni-bremen.de
    - to_pa@uni-bremen.de
