language: python
python:
  - "3.6"

script: python -m unittest discover --start-directory ./enviro/compute_tests

notifications:
  email:
    - a.haselsteiner@uni-bremen.de
    - kawindme@uni-bremen.de
    - janlehmk@uni-bremen.de
    - tobiaspape.tp@gmail.com